config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :sends, only: [:index]
  resources :followees
  # Defines the root path route ("/")
  root "sends#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/area.rb
class Area < ApplicationRecord
  validates :area_id, uniqueness: true, presence: true
  validates :area_name, presence: true
end

app/models/followee.rb
class Followee < ApplicationRecord
  belongs_to :user
  validates :username, uniqueness: { scope: [:user_id]}, presence: true
  #TODO: Add
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :followees
  validates :followees, uniqueness: true
end

app/controllers/followees_controller.rb
class FolloweesController < ApplicationController
  def create
    @followee = current_user.followees.new(followee_params)

    if @followee.save
      redirect_to :root
    else
      p @followee.errors.full_messages
    end
  end

  def show # I put the destroy function here because I could not get the link to make a DESTROY request instead of a GET request
    @followee = Followee.find(params[:id])
    @followee.destroy

    redirect_to root_path
  end

  def destroy # Not currently being used because of reason mentioned above
    @followee = Followee.find(params[:id])
    @followee.destroy

    redirect_to root_path
  end

  private

  def followee_params
    params.require(:followee).permit(:username, :realname, :id)
  end
end

app/controllers/sends_controller.rb
class SendsController < ApplicationController
  def index
    if user_signed_in?
      @followees = current_user.followees

      @data = {users: [], sends: []}
      
      # Replace this with commented section below for live data
      # @data = filler_data

      # TODO: Add threading - will require refactoring code so that we don't multiple tasks trying to write to the database at the same time.
      # Looks some thing like: 
      # threads = []
      # threads << Thread.new {task}
      # threads.each { |thr| thr.join }

      @followees.each do |followee|
        user_info, user_sends = helpers.scrape_sendage_sends(followee, 5)
        user_sends.each do |send|
          area_info = get_area_info(send[:area_id])
          area_name = area_info["name"]
          area_parents = area_info["parents"]
          send[:area_name] = area_name
          send[:area_parents] = area_parents.reverse()
        end
        @data[:users] << user_info
        @data[:sends] += user_sends
      end

      @followee = current_user.followees.new
    else
      redirect_to new_user_session_path
    end
  end

  private

  def followee_params
    params.require(:followee).permit(:username, :realname, :user_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followees_helper.rb
module FolloweesHelper
end

app/views/sends/_feed.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div class="flex flex-col">
  <div class="-my-2 sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="table-fixed min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-2 pl-16 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Climb
              </th>
              <th scope="col" class="px-2 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Comment
              </th>
              <th scope="col" class="px-2 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Date
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <%sends.each do |send|%>
              <tr>
                <td class="px-2 py-2">
                  <div class="flex items-center">
                    <div class="flex-shrink-0 h-10 w-10">
                      <img class="h-10 w-10 rounded-full" src=<%=send[:profile_pic]%> alt="">
                    </div>
                    <div class="ml-4">
                      <div class="text-xs text-gray-900">
                        <%=send[:realname]%>
                      </div>
                      <div class="text-sm font-medium text-gray-900">
                        <%=send[:name]+", "+send[:grade]%>
                          <span>
                            <%case send[:send_type]%>
                            <%when "redpoint"%>
                                <span class="px-2 text-xs inline-flex font-semibold rounded-full bg-red-100 text-red-800"><%=send[:send_type].capitalize%></span>
                            <%when "flash"%>
                                <span class="px-2 text-xs inline-flex font-semibold rounded-full bg-gray-200 text-gray-800"><%=send[:send_type].capitalize%></span>
                            <%when "onsight"%>
                                <span class="px-2 text-xs inline-flex font-semibold rounded-full bg-yellow-100 text-yellow-800"><%=send[:send_type].capitalize%></span>
                            <%end%>
                          </span>
                      </div>
                      <div class="text-xs text-gray-500">
                        <%parents_str = ""%>
                        <%send[:area_parents].each do |parent|%>
                          <%parents_str += parent + " > "%>
                        <%end%>
                        <%=parents_str + send[:area_name]%>
                      </div>
                    </div>
                  </div>
                </td>
                <td class="px-2 py-2 ">
                  <div class="text-xs text-gray-500 italic"><%=send[:comment]%></div>
                </td>
                <td class="px-2 py-2 whitespace-nowrap text-sm text-gray-500">
                  <%=send[:date]%>
                </td>
              </tr>
            <%end%>
            <!-- More people... -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/sends/_following.html.erb
<div class="flex flex-col">
  <div class="px-6 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-left inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Following
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
          <%followees.each do |followee|%>
            <tr>
              <td class="px-2 py-2 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="flex-shrink-0 h-10 w-10">
                    <img class="h-10 w-10 rounded-full" src=<%=followee[:profile_pic]%> alt="">
                  </div>
                  <div class="ml-4 flex-col">
                    <div class="text-sm font-medium text-gray-900">
                      <%=followee[:realname]%>
                    </div>
                    <div class="text-xs font-medium text-gray-500 text-decoration-line: underline">
                    <%= link_to "unfollow", followee_path(followee[:id]), method: :delete %> 
                    </div>
                  </div>
                </div>
              </td>
            </tr>
            <%end%>
            <tr>
              <td class="whitespace-nowrap">
                <div class="flex items-center">
                  <%=render "form"%>
                </div>
              </td>
            </tr>

            <!-- More people... -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/sends/_form.html.erb
<% if @followee.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@followee.errors.count, "error") %> prohibited this followee from being saved:</h2>
 
    <ul>
    <% @followee.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @followee, class: "w-48 text-left text-xs font-medium text-gray-500 uppercase tracking-wider" do |form| %>
    <%= form.text_field :username, class: 'border-none h-12 w-48 text-left text-sm placeholder-italic placeholder-gray-500 text-gray-900', placeholder:"Add new followee..."%><br>
    <%= form.submit "Submit", class: 'border-none w-48 text-center text-sm text-blue-500'%>
<%end%>

app/views/sends/index.html.erb
<main class="flex flex-row">
    <% followees = @data[:users]%>
    <% sends = @data[:sends].sort_by {|send| send[:date]}.reverse%>

    <div class="justify-self-start inset-y-0 left-0">
        <%= render 'following', followees: followees%>
    </div>
    <div class="container mx-auto">
        <%= render 'feed', sends: sends %>
    </div>
</main>